### ISSUE TITLE
login hangs when using yubikey as MFA

### ISSUE THREAD

**Issue by squalou** [ThatOneCalculator/google-chat-tauri#3]
see https://github.com/ThatOneCalculator/google-chat-tauri/issues/1 for a screenshot.

Using a security key usually requires the browsers to ask for permission to use them.

Tested with app 0.0.6 on PopOS : the login window hangs waiting after login / password is entered.

**Comment by pavriet-boxtal** [comment]
Hello,

No issue for me
app : 0.0.6
ubuntu 22.04.3 LTS

**Comment by squalou** [comment]
will try again with a "decent" connexion

apparently google expects people to have a gigabit-rated connexion to use a messaging app :)

**Comment by ThatOneCalculator** [comment]
Out of curiosity, can you download GNOME Web and see if it works on the browser?

**Comment by squalou** [comment]
Good guess : it does not work either.

**Comment by ThatOneCalculator** [comment]
I'll close this as out of scope, a bug report should be filed here under webkit2gtk: https://bugs.webkit.org/

**Comment by ThatOneCalculator** [comment]
...or maybe with Pop!_OS? Since it worked for @pavriet-boxtal

**Comment by squalou** [comment]
yeah it's weird, but obviously not something you can fix here :)
Discovered some 2022-ish issues on webkitgtk about this, not addressed yet.

That's probably the difficulty with Tauri approach : you'll always have a behaviour dependant on html rendering engine installed on end-user OS.

Probably flatpak will help in the end (I did not try flatpak version of epiphany, maybe it works btw)

**Comment by ThatOneCalculator** [comment]
You might be able to right click -> reload on your system webview impl
