### ISSUE TITLE
systray notification icon issues

### ISSUE THREAD

**Issue by squalou** [ThatOneCalculator/google-chat-tauri#4]
systray icon not suited to dark theme.

see in the middle below :

![image](https://github.com/ThatOneCalculator/google-chat-tauri/assets/4623644/1a2375b0-8757-42dd-a522-9748197537f7)

Also I did not see it reflect changes in the status (connected / disconnected / unread messages )

**Comment by ThatOneCalculator** [comment]
> systray icon not suited to dark theme.

Aware, working on it

> Also I did not see it reflect changes in the status (connected / disconnected / unread messages )

Hasn't been implemented yet

**Comment by ThatOneCalculator** [comment]
Will get around to this. Sorry I haven't been showing this a lot of love, I ended up daily driving your project lol

**Comment by ThatOneCalculator** [comment]
Closed as of 0.0.8
